POST http://localhost:3000/
Content-Type: application/json
    {
        "username": "test",
        "password": "test"
    }



#### Register
curl -X POST http://localhost:3000/register \
-H "Content-Type: application/json" \
-d '{"username":"user1", "password":"password1"}'
